app: "fg-ms"
path: "/users"
namespace: "core-services"
deployment:
  replicas: 1
  port: 80
  image:
    host: registry.digitalocean.com
    registry: fg-registry
    repository: "nginx"
    tag: "latest"
    pullPolicy: "IfNotPresent"
    pullSecrets: "fg-registry"
  secrets:
    dopplerToken:
      enabled: true
      prefix: "doppler"
  linkerd:
    enabled: true
    proxyCPURequest: "10m"
    proxyMemoryRequest: "20Mi"
service:
  type: "NodePort"
  protocol: "TCP"
  port: 80
  targetPort: 80
  nodePort: 30080
  class: "nginx"
ingress:
  tls:
    host: "dev.api.flgd.space"
    secretName: "fg-tls"
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  cpuUtilizationPercentage: 50
  memoryUtilizationPercentage: 50
