app: "fg-ms"
path: "/users"
deployment:
  replicas: 1
  port: 80
  image:
    host: registry.digitalocean.com
    registry: fg-registry
    repository: "nginx"
    tag: "latest"
    pullPolicy: "IfNotPresent"
    pullSecrets: "fg-registry"
  secrets:
    dopplerToken:
      enabled: true
      prefix: "doppler"
service:
  type: "NodePort"
  protocol: "TCP"
  port: 80
  targetPort: 80
  nodePort: 30080
  class: "nginx"
ingress:
  annotations:
    sessionAffinity:
      type: "cookie"
      cookieName: "route"
      mode: "persistent"
