app: "fg-ms"
deployment:
  replicas: 1
  port: 80
  image:
    host: registry.digitalocean.com
    registry: fg-registry
    repository: "nginx"
    tag: "latest"
    pullPolicy: "IfNotPresent"
    pullSecrets: "fg-registry"
  resources:
    limits:
      cpu: "80m"
      memory: "128Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  secrets:
    dopplerToken:
      enabled: true
      prefix: "doppler"
service:
  type: "NodePort"
  protocol: "TCP"
  port: 80
  targetPort: 80
  nodePort: 30080