apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
spec:
    replicas: {{ .Values.deployment.replicas }}
    selector:
      matchLabels:
        app: {{ .Values.app }}
    template:
        metadata:
            labels: 
              app: {{ .Values.app }}
            annotations:
              {{ if .Values.deployment.linkerd.enabled }}
              config.linkerd.io/proxy-cpu-request: {{ .Values.deployment.linkerd.proxyCPURequest }}
              config.linkerd.io/proxy-memory-limit: {{ .Values.deployment.linkerd.proxyMemoryLimit }}
              config.linkerd.io/proxy-memory-request: {{ .Values.deployment.linkerd.proxyMemoryRequest }}
              {{ end }}
        spec:
            containers:
            - name: {{ .Values.app }}
              image: "{{ .Values.deployment.image.host }}/{{ .Values.deployment.image.registry }}/{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
              imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
              {{ if .Values.deployment.resources }}
              resources:
              {{ if .Values.deployment.resources.limits }}
                limits:
                  {{ if .Values.deployment.resources.limits.cpu }}
                    cpu: {{ .Values.deployment.resources.limits.cpu }}
                  {{ end }}
                  {{ if .Values.deployment.resources.limits.memory }}
                    memory: {{ .Values.deployment.resources.limits.memory }}
                  {{ end }}
              {{ end }}
              {{ if .Values.deployment.resources.requests }}
                requests:
                  {{ if .Values.deployment.resources.requests.cpu }}
                    cpu: {{ .Values.deployment.resources.requests.cpu }}
                  {{ end }}
                  {{ if .Values.deployment.resources.requests.memory }}
                    memory: {{ .Values.deployment.resources.requests.memory }}
                  {{ end }}
              {{ end }}
              {{ end }}
              ports:
               - containerPort: {{ .Values.deployment.port }}
                 protocol: TCP
              {{ if .Values.deployment.secrets.dopplerToken.enabled }}
              envFrom:
                - secretRef:
                    name: "{{ .Values.deployment.secrets.dopplerToken.prefix }}-{{ .Values.app }}"
              {{ end }}
            imagePullSecrets:
              - name: {{ .Values.deployment.image.pullSecrets }}