{{ if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
 {{ if .Values.hpa.targetCPUUtilizationPercentage }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage }}
 {{ end }}
 {{ if .Values.hpa.targetMemoryUtilizationPercentage }}
  targetMemoryUtilizationPercentage: {{ .Values.hpa.targetMemoryUtilizationPercentage }}
 {{ end }}
{{ end }}