apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}

spec:
    selector:
      app: {{ .Values.app }}
    ports:
        - name: {{ .Values.app }}
          port: {{ .Values.service.port }}
          targetPort: {{ .Values.deployment.port }}